WebApp/Controllers/TaskItemMvcController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using WebApp.Repository;

namespace WebApp.Controllers
{
    public class TaskItemMvcController : Controller
    {
        private readonly IItemsRepo _itemsRepo;
        
        public TaskItemMvcController(IItemsRepo itemsRepo)
        {
            _itemsRepo = itemsRepo;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Index() => View("Index",_itemsRepo.GetItemsAsync());

        [Authorize]
        public IActionResult Create() => View();

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Create(TaskItem item)
        {
            if (!ModelState.IsValid)
            {
                return View(item);
            }
            await _itemsRepo.AddItemAsync(item);
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<ActionResult> Edit(string id)
        {
            var item = await _itemsRepo.GetItemAsync(id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Edit(TaskItem item)
        {
            if (!ModelState.IsValid)
            {
                return View(item);
            }
            await _itemsRepo.UpdateItemAsync(item.Id, item);
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var item = await _itemsRepo.GetItemAsync(id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        [HttpPost]
        [ActionName("Delete")]
        [Authorize]
        public async Task<ActionResult> DeleteConfirmedAsync(string id)
        {
            await _itemsRepo.DeleteItemAsync(id, User.Identity.Name);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Details(string id) => 
            View(await _itemsRepo.GetItemAsync(id));
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CosmosTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="/">CosmosTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/reactapp">React-version</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="TaskItemMvc">MVC-version</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/reactapp/anotherPage">Another Page</a>
                        </li>
                    </ul>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <span class="navbar-text" style="margin-right: 5px">Logged in as</span>
                        <span class="navbar-text text-dark">@User.Identity.Name</span>
                        <a asp-page="/Login" class="nav-link text-dark">Logout</a>
                    }
                    else
                    {
                        <a asp-page="/Login" class="nav-link text-dark">Login</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CosmosTest
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>